CREATE DATABASE CADASTRO 
DEFAULT CHARACTER SET utf8 
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE PESSOAS(

ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(30) NOT NULL,
NASCIMENTO DATE,
SEXO ENUM('M','F'),
PESO DECIMAL(5,2),
ALTURA DECIMAL(3,2),
NACIONALIDADE VARCHAR(20) DEFAULT 'Brasil',
PRIMARY KEY(ID)

) DEFAULT CHARSET = utf8;

